---
- name: Prepare environment
  tags: prepare_env
  block:
    - name: Install prerequisites
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - maven
        - openjdk-11-jdk-headless
        - docker-ce
      tags: install_prereqs

    - name: Render Docker Compose file
      template:
        src: "{{ playbook_dir }}/compose/config/docker-compose.yaml.j2"
        dest: "{{ tests_directory }}/docker-compose.yaml"
      tags: render_config

    - name: Stop containers after testing
      command: docker-compose down
      args:
        chdir: "{{ tests_directory }}"
      register: result_stop_containers
      ignore_errors: true
      when: play_recap is success
      tags: stop_services

    - name: Start Docker services
      command: docker-compose up -d
      args:
        chdir: "{{ tests_directory }}"
      tags: start_services

    - name: Build and run tests
      block:
        - name: Clean and verify project
          shell: |
            cd "{{ tests_directory }}" &&
            mvn clean verify -Dsurefire.skip=false -Dbrowser.type={{ browser_type }}
          when: browser_type is defined
          tags: run_tests

        - name: Delete target directory after testing
          file:
            path: "{{ tests_directory }}/target"
            state: absent
          ignore_errors: true
          tags: cleanup_target
